<Project>

  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NeutralLanguage>ru-RU</NeutralLanguage>
    <Company>WarehousePlanAutomation</Company>
    <Product>Формирование плана склада</Product>
    <Version>1.5.0</Version>
  </PropertyGroup>

</Project>
